---
title: 'Overview of EPPN2020 network'
output: html_document
---
```{r, echo = F}
knitr::opts_chunk$set(echo = F)
```

```{r library, echo = FALSE, warning= FALSE, message=FALSE}
library(remotes)
library(phisWSClientR)
library(RColorBrewer)
library(ggplot2)
library(stringr)
library(data.table)
library(dplyr)
```

In the EPPN2020 network we have several installations using PHIS information system. This system allows the usage of same standards making cross-installation real time visualization possible. Here is an example of what could be done with such a system. 
This is just counting the number of Scientific Objects.

```{r instances name and address, echo = F}
instancesApi = c("147.100.175.121:8080/phenomeDiaphenAPI/rest/", "opensilex.org/openSilexAPI/rest/", "147.100.175.121:8080/phenomeAgrophenAPI/rest/", "147.100.175.121:8080/phenomePheno3cAPI/rest/", "147.100.175.121:8080/phenomePhenoviaAPI/rest/", "147.100.175.121:8080/phenomePhenofieldAPI/rest/", "138.102.159.36:8080/phenomeEphesiaAPI/rest/")
instancesNames = c("Diaphen", "OpensilexDemo", "Agrophen", "Pheno3C", "Phenovia", "PhenoField", "Ephesia")

inst = data.frame(name = instancesNames, api = instancesApi)
inst
```

```{r data query, echo = F, warning=F, message=F, include=F}
pal1 = brewer.pal(name = 'Set3', n = 12)
pal2 = brewer.pal(name = 'Dark2', n = 8)

scientificObjectOverview = function(inst){
  ## This function has two improvements keypoints : decypher the URI to extract the Experiment and the Year (if I could avoid the getExperiment web service)
  initializeClientConnection(apiID="ws_private", url = inst['api'])
  aToken = getToken("guest@opensilex.org","guest")
  count <- getScientificObjects(aToken$data, pageSize = 1)$totalCount
  scientificObjects <- getScientificObjects(aToken$data, pageSize = count)
  wsQuery = scientificObjects$data  
  
  tbl = table(wsQuery$rdfType, dnn = c('Type'), deparse.level = 2)
  typeDF = data.frame("Installation" = inst['name'], tbl,
                      "rdfType" = str_sub(names(tbl), start = str_locate(names(tbl), pattern = "#")[,1]+1, end = str_locate(names(tbl), pattern = "#")[,1]+16))
  
  exp = table(wsQuery$experiment, dnn = c("experimentURI"))
  expDF = data.frame("Installation" = inst['name'], exp,
                     "Year" = str_sub(names(exp), start = str_locate(names(exp), pattern = "20")[,1], end = str_locate(names(exp), pattern = "20")[,2]+2),
                     "Experiments" = sapply(str_split(names(exp), pattern = "/"), FUN = function(X){X[5]})
                     )
  return(data = list(typeDF, expDF))
}

graphData = apply(X = inst, MARGIN = 1, FUN = scientificObjectOverview)
```

# RDFTYPE

```{r rdftype data, echo = F}
##---- DATA
typeData = data.frame()
for( i in 1:length(graphData)){
  typeData = rbind(typeData, graphData[[i]][[1]])
}
typeData[, -2]
```

```{r rdftype viz}
##---- VIZ
g1 = ggplot(data = typeData) +
  geom_col(aes(x = rdfType, y = Freq, fill = Installation)) + 
  labs(x = "Type of Scientific Object") + 
  labs(y = "Number of Scientific Objects") + 
  labs(title = "Number of Scientific Objects of various type", subtitle = "Colored by installation")
g1
```

```{r pie chart data}
mycols <- c("#0073C2FF", "#EFC000FF", "#868686FF", "#CD534CFF")
count.data <- typeData %>%
  dplyr::group_by(rdfType)%>%
  summarise(total = sum(Freq))%>%
  mutate(prop = round(total/sum(total), digits = 2))%>%
  mutate(lab.ypos = 1-round(cumsum(prop) - 0.5*prop, digits = 2))%>%
  arrange(desc(prop))
count.data
```

```{r pie chart viz}
g4 = ggplot(count.data, aes(x = "", y = prop, fill = rdfType)) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar("y", start = 0, direction = -1)+
  geom_text(aes(y = lab.ypos, label = prop), color = "white", size=5)+
  scale_fill_manual(values = pal2) +
  theme_void() +
  labs(title = "Proportion of Scientific Objects within the network", subtitle = "Across all years")
g4
```


# Experiments

```{r experiments data, echo = F}
expData = data.frame()
for( i in 1:length(graphData)){
  expData = rbind(expData, graphData[[i]][[2]])
}
expData = data.table(expData, keep.rownames = F)
expData$Year = ordered(x = expData$Year, c("2015","2016","2017","2018","2019"))
expData[order(Year),-2]

expDF = expData[ Installation == "Diaphen",]
```

```{r experiments viz}
g21 = ggplot(data = expData) +
  geom_bar(aes(x = Experiments, weight = Freq, fill = Installation)) +
  labs(x = "Experiments") + 
  labs(y = "Number of Scientific Objects") + 
  labs(title = "Number of Scientific Objects across different experiments", subtitle = "Colored by Installations") + 
  theme(axis.text.x =  element_text(size = 8, angle = 80,  hjust = 1))
g21
```

```{r experiments viz diaphen}
g22 = ggplot(data = expDF, aes(Experiments)) +
  geom_bar(aes(weight = Freq), fill = c(pal2, pal1)[1:15]) +
  labs(x = "Experiments") + 
  labs(y = "Number of Scientific Objects") + 
  labs(title = "Number of Scientific Objects across different experiments", subtitle = "Installation : DIAPHEN")+ 
  theme(axis.text.x =  element_text(size = 7, angle = 80,  hjust = 1))
g22
```

# Year

```{r year viz}
g31 = ggplot(data = expData) +
  geom_col(mapping = aes(x = Year, y = Freq, fill = Installation ), position = "stack") +
  labs(x = "Year") + 
  labs(y = "Number of Scientific Objects") + 
  labs(title = "Evolution of Scientific Objects over time" , subtitle = "Colored by different installations")
g31
```

```{r year viz diaphen}
g32 = ggplot(data = expDF) +
  geom_col(mapping = aes(x = Year, y = Freq, fill = Experiments ), position = "stack") +
  labs(x = "Year") + 
  labs(y = "Number of Scientific Objects") + 
  labs(title = "Evolution of Scientific Objects over time" , subtitle = "Installation: DIAPHEN \nColored by different Experiments")
g32
```
